apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: data-tier
  serviceName: mongo
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
        tier: data-tier
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:latest
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          valueFrom:
            secretKeyRef:
              name: db-tier-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          valueFrom:
            secretKeyRef:
              name: db-tier-secret
              key: MONGO_ROOT_PASSWORD
        ports:
        - name: mongo
          containerPort: 3306
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: config
          mountPath: /config
        # - name: secret
        #   mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: config
        configMap:
          name: mongo-config
          items:
          - key: mongo.conf
            path: /config
      # - name: secret
      #   secret:
      #     name: db-tier-secret
      #     items:
      #     - key: MONGO_ROOT_USERNAME
      #       path: /etc/mongo-credentials
      #     - key: MONGO_ROOT_PASSWORD
      #       path: /etc/mongo-credentials                          