version: "3.8"

services:
  item-app:
    container_name: item-app
    image: ramafebri/item-app:v1
    ports:
      - 80:8080
    networks:
      - item-app-net
    environment:
      NODE_ENV: production
      DB_HOST: item-db
    depends_on:
      - item-db
    restart: on-failure

  item-db:
    container_name: item-db
    image: mongo:3
    ports:
      - 27017:27017
    networks:
      - item-app-net
    volumes:
      - "app-db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: on-failure

volumes:
  app-db:
    name: app-db

networks:
  item-app-net:
    name: item-app-net
    driver: bridge