apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-tier
  labels:
    app: backend
    tier: be
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: be
  template:
    metadata:
      labels:
        app: backend
        tier: be
    spec:
      containers:
      - name: server
        image: ramafebri/karsajobs:latest
        ports:
          - containerPort: 8080
        env:
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: mongodb://$(MONGO_SERVICE_HOST):$(MONGO_SERVICE_PORT)
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: db-tier-secret
                key: MONGO_ROOT_USERNAME
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: db-tier-secret
                key: MONGO_ROOT_PASSWORD                       